# Generated by Django 3.0.6 on 2020-07-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_Dives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='upcoming_dive_images')),
            ],
        ),
    ]
