# Generated by Django 3.0.6 on 2020-07-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divepost',
            name='image1',
            field=models.ImageField(default=None, upload_to='recent_dive_images'),
        ),
    ]
