# Generated by Django 3.0.6 on 2020-06-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='divers',
        ),
        migrations.AddField(
            model_name='post',
            name='dive_site',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
