# Generated by Django 3.0.6 on 2020-07-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_divepost_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='divepost',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='recent_dive_images'),
        ),
        migrations.AddField(
            model_name='divepost',
            name='image3',
            field=models.ImageField(default='default.jpg', upload_to='recent_dive_images'),
        ),
        migrations.AlterField(
            model_name='divepost',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='recent_dive_images'),
        ),
    ]
